version: "3.9"

services:
  api:
    build: ./api # 独自のimageを使用する場合はbuildを使う
    ports:
      - 8080:8080
  db:
    image: postgres:15 # dockerhubから既成のものを使用
    ports:
      - 5432:5432 # 事前に決まっているport番号
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d # ホスト側のファイルをコンテナ側にマウントする

volumes:
  db-storage: # volume領域の宣言
