version: "3.9"

services:
  api:
    build: ./api
    ports:
      - 8080:8080
# 以下のdocker commandと同じ処理
# $ docker image build -t api-img ./api
# $ docker container run -d --name api -p 8080:8080 api-
# docker compose upで起動する
