version: "3.9"

services:
  api:
    build: ./api # 独自のimageを使用する場合はbuildを使う
    ports:
      - 8080:8080
    depends_on: # service間の依存関係を記述。起動する順番を制御。dbコンテナ→apiコンテナの順番で起動。
      - db
  db:
    image: postgres:15 # dockerhubから既成のimageを使用
    ports:
      - 5432:5432 # postgresで事前に決まっているport番号
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appdb
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d # ホスト側のファイルをコンテナ側にマウントする

volumes:
  db-storage: # volume領域の宣言
